### ISSUE TITLE
Update documentation for V1

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/urql#140]
There are a number of changes which need to be documented for V1. A changelog will also be required to document any breaking changes.

Also, a large amount of the API usage being documented is now provided in the Typescript declarations (see #138). TSDoc output should be able to automate API documentation for use in the README.md or a Wiki page.

#### Tasks
- [ ] Update README.md
  - [ ] Document API changes
  - [ ] Add updated exchange documentation
  - [ ] Replace README.md API documentation with that produced by TSDoc.
- [ ] Add CHANGELOG.md
- [ ] MIGRATION.md
  - [x] Create MIGRATION.md with changes
  - [ ] Add links to documentation

**Comment by kitten** [comment]
Going to close this for now in favour of the pending #181 PR.
