### ISSUE TITLE
[Umbrella] The new documentation

### ISSUE THREAD

**Issue by JoviDeCroock** [FormidableLabs/urql#548]
# Structure

- basics
  - Setting up the client
  - Querying data
  - Mutating data
- Advanced
  - events (polling + subscriptions)
  - ssr (next-urql, ssrExchange)
- normalised cache
  - getting started
  - recipes
- integrations
   - preact
   - future.... (svelte, ...)
- showcase
  - who uses urql
  - demo applications
  - blog posts
  - 3th party exchanges
- Architecture
  - why have we opted for x or y
- API
  - in-depth options, ... similar to what we have now

## Basics

Here we'll cover the basics, this should showcase how easy it is to get started with urql.

### Setting up the client

An example of setting up our client with just a url and then providing it to our component tree. This should also touch on the `fetchOptions` to provide arbitrary information to the fetch-step.

These to me seem like the only two crucial options to getting started.

### Querying data

This should show `useQuery` in action and mention that we also have a `Query` render-props component with the same API.

Options to highlight:
- requestPolicy (explain all of them as well)
- skip
- pause

Don't use graphql-tag just use normal strings for simplicity

### Mutating data

Here we have to show `useMutation` and mention the component counter-part.
This should highlight the difference between the `.then` approach and the hook-result one

```
const [result, execute] = useMutation

execute().then(data) vs result.data
```

Don't use graphql-tag just use normal strings for simplicity

> I'd end this chapter with a set-up codesandbox of this, I think there should be one on the formidable account.

## Advanced

First we have to cover the concept of exchanges and how we can use these to enhance our API's

### Devtools

Show how to install devtools and highlight what can be done with it:
- explore cache
- see operations

### Events

Here we'll come back to polling for the `useQuery` hook and continue on to subscriptions and the exchange for it.

We highlight `useSubscription`, `subscriptionExchange` and how to add these to the client.

> I'd end this chapter with a set-up codesandbox of this, I think there should be one on the formidable account.

### SSR

We talk about how next-urql saves you the time of setting up urql with ssr for next and how to set up the ssrExchange to rehydrate your cache.

> This can refer to the `next-urql` example

#### graphql-tag

When you start using fragments you need graphql-tag, you can't just do the normal string.

## Normalised cache

We should start off with describing what a normalised cache means for the user.

### Getting started

Highlight that if we're transitioning from default doc-cache to normalised cache that the user should make sure all the mutations are actually returning the mutated data in their result this way the normalised cache can automatically update said entities.

### Recipes

- [populateExchange](https://github.com/FormidableLabs/urql/blob/master/docs/graphcache/Populate.md)
- [cache keys](https://github.com/FormidableLabs/urql/blob/master/docs/graphcache/keys.md)
- resolving values (and entities) found [here](https://github.com/FormidableLabs/urql/blob/master/docs/graphcache/resolvers.md)
- updates --> updating === automatic, adding and deleting from a list not so much found [here](https://github.com/FormidableLabs/urql/blob/master/docs/graphcache/updates.md)
- [schema-awareness and partial results](https://github.com/FormidableLabs/urql/blob/master/docs/graphcache/schema.md)
- persisted-stores only an example of it available now
- [optimistic updates](https://github.com/FormidableLabs/urql/blob/master/docs/graphcache/optimistic.md)
- [help](https://github.com/FormidableLabs/urql/blob/master/docs/graphcache/help.md)
- how to introspect

Most of these are present in the graphcache docs but very spread out and maybe a bit too thin.

Also a bit of explanation about the [architecture of graphcache](https://github.com/FormidableLabs/urql/blob/master/docs/graphcache/architecture.md)

## Architecture

Highlight why certain decisions were made, these will have to be collected.

## API

This will be very similar to our current API but we need to check if everything is still up to date

### Who uses urql

<collect companies>

### Demo applications

- threed-web [code](https://github.com/JoviDeCroock/threed-web)

### Blog posts

<collect blog posts>

### Thirth party exchanges

- hashed queries

**Comment by boygirl** [comment]
@JoviDeCroock awesome! Will these all follow the same url scheme? i.e. `/docs/basics/setting-up-the-client#some-anghor-tag` If not, it would be super helpful if you could add expected deviations to this document.

**Comment by JoviDeCroock** [comment]
I would try and have a good amount of anchor tags as in, explanations, examples this makes it easier for us to link from issues, tweets, ... I think the standard is on titles which would be sufficient. I don't see any potential deviations at the moment.

**Comment by kitten** [comment]
**Writing Styleguide**

To align on how these documents and pages are written we'll decide on a general list of guidelines that have to be applied so each page follows a similar writing style and structure, even when they've been written by different authors.

- Every page starts with an `h1` that is the _long form_ of its title which shows up in the sidebar (can be overriden using `frontmatter.title`).
- Every page starts with an introduction, explaining what it will teach and/or document.
- If a page contains splits/documentation for multiple frameworks (e.g. Svelte, React, Preact) the introduction should include a note of them and possible internal anchor links. (e.g. "This section applies to multiple frameworks. [Exception:] If you're using Svelte, read about [X] here.")
- If a page contains splits/documentation for multiple frameworks, they should be combined as often as possible, meaning a minimal amount of duplication.
- Pages should use `h2` and `h3` liberally and frequently. They're used for search, split up the content nicely, and generally make the page feel shorter than it may actually be.
- When a topic is being explained, we should stop explaining outside of the realm of `urql` / GraphQL, include some explanation if it's related to "tricky" details with the framework (React / Preact / etc, e.g. "gotchas with hooks in React"), but everything else (JS-language features, etc) shouldn't be mentioned and knowledge should be assumed.
- Every part of the documentation should still be complete and understandable if the user wasn't reading the code samples. (As far as possible, since this doesn't apply to step-by-step guides)
- Links to other pages (e.g. "Read more...") should be phrased to include what they're linking to and follow the general phrasing of: "Read more about [normalised caching]." (avoid the pronoun game, e.g. "it", "that", ...)
- Prefer the use of "we" over "you". This can refer to both "us" as the authors of `urql` — e.g. "we made the decision to ...", or "us" as in the group of the reader and the author — e.g. "we are now going to write some code to do [X]"
- Every group of pages (sidebar group) should have an index page with minimal content explaining what the group is all about and possibly link to the sub-pages.

**Comment by levrik** [comment]
That's very good news. The main reason why I'm staying away from URQL is its documentation.
Maybe I'll give it a try again when the docs are there.

**Comment by kitten** [comment]
Work on #556 is almost complete, however we're missing just a couple of little tasks that need to be completed:

- [ ] The "Server-side Rendering" page is missing a lot of content on setting this up, `react-ssr-prepass`, and a `next-urql` guide
- [ ] "Auto-populate" doesn't offer up information on why you'd use it and what the motivation is (also a note that it's experimental)
- [ ] The Graphcache pages don't cover a lot of the why and common use-cases like invalidation, lists, pagination
- [ ] We're missing an "Offline" page (for persistence)
- [ ] Fix formatting on the API docs and add the API content for `@urql/exchange-graphcache`

**Comment by boygirl** [comment]
Docs TODOS:

Blocking:
- many (but not all) of the relative links within the markdown are 404ing. Sounds like Phil is already on it.
- header `urql` link back to the home page is not working. Errors in the console

Nice to have:
- Should "API" be above "Showcase" in the sidebar?
- missing favicon
- on small screen sizes clicking on the main article should close the sidebar if it is open
- urql logo in the sidebar should link back to home page
- heading should be linkable anchor tags

**Comment by boygirl** [comment]
Links that are still 404ing:
- in `/basics/queries/` 
     - the link to `/api/urql.md/#components`
     - the link to `/docs/errors/`
     - the link to `/api/urql.md/#usequery`
    - the link to `/docs/mutations/`

... Still a bunch. Too many to document all individually

**Comment by boygirl** [comment]
Should external links open in a new tab?

**Comment by boygirl** [comment]
Remaining broken links:
- in `/docs/advanced/subscriptions/` the link to `docs/basics/querying-data/`
- `/docs/graphcache/#features` link in the markdown does not scroll to a section, so the link feels broken
` in `docs/graphcache/computed-queries/` a link labeled "below" links to `/docs/graphcache/#cache.resolve`, a section that does not exist in `/docs/graphcache/`.  From `/docs/graphcache/#cache.resolve` other links are all incorrectly resolved, resulting in 404s
- in `docs/api/core/` `docs/api/#clientquery` links to a section that doesn't exist in `docs/api/`. Navigating to any links from `docs/api/#clientquery`  404s. (ditto `docs/api/#createrequest`)

**Comment by kitten** [comment]
Regarding two of the tasks:

- "Showcase" is in front of "API" because we expect "API" to be pages that the reader would explicitly be linked to or actively go to when they need to read up on some API details, so it goes last in priority.
- Setting `target="_blank"` on external links is regarded as 'changing the default behaviour' so it's not recommended, since it's unexpected. [CSS Tricks](https://css-tricks.com/use-target_blank/) has a good explanation on that

**Comment by BjoernRave** [comment]
It might make sense to make the Exchanges a main point, with a description on the main page and have the different exchanges as children, together with a short explanation of what they are and do + usage tips

**Comment by kitten** [comment]
@BjoernRave Hey, thanks for having a look! 🙏

The top right is reserved for the search bar but we’re looking to have a GitHub edit button on every page eventually, once we get to adding that 👍 

We’re currently looking at where to put the list of exchanges. We may not want to put it where we’re just explaining what they are, but I’ll have a look 😅 That being said, most things will be exchanges, and we expected people to instead search for topical things instead, e.g “Retrying”, “Normalized Caching”, etc, rather than a full list

**Comment by kitten** [comment]
Closing this for now, since we've got all "shortcomings" tracked :+1:
